### ISSUE TITLE
Display mismatching version output with a table

### ISSUE THREAD

**Issue by bmish** [bmish/check-dependency-version-consistency#188]
It could make sense to use a table to display the data. Kind of like ESLint per-rule performance output: https://eslint.org/docs/developer-guide/working-with-rules-deprecated#per-rule-performance

```
Found 2 dependencies with mismatching versions.

| eslint | Usages | Found in |
| ------ | ------ | -------- |
| ^7.8.9 | 1      | package1 | 
| ^8.0.0 | 1      | package2 |

| sinon  | Usages | Found in           |
| ------ | ------ | ------------------ |
| 1.2.0  | 2      | package1, package2 |
| ^2.0.0 | 1      | package3           |
```

`console.table` is one way to print tables but it's very limited and doesn't display things nicely. https://www.npmjs.com/package/table is probably the way to go.

**Comment by ddzz** [comment]
A table would add unnecessary formatting that clutters the output. I think it would be a better idea to use an output format similar to what's seen in tests or linters.
