### ISSUE TITLE
Add option to update inconsistencies to a specific version

### ISSUE THREAD

**Issue by ddzz** [bmish/check-dependency-version-consistency#190]

**Comment by bmish** [comment]
I'm not sure how that would work. I think it would be more useful to offer [general fixing strategies](https://github.com/bmish/check-dependency-version-consistency/issues/191) as opposed to having the user specify specific versions to fix to.

There are other general package management tools like [lerna](https://github.com/lerna/lerna) or [yarn workspace](https://classic.yarnpkg.com/en/docs/cli/workspace/) that could help with more specific package update commands.
