### ISSUE TITLE
Run `yarn install` when `--fix` option is used

### ISSUE THREAD

**Issue by ddzz** [bmish/check-dependency-version-consistency#201]

**Comment by bmish** [comment]
Interesting idea. I'd prefer these were not tied together however. I'd rather be able to run `check-dependency-version-consistency`, review the results with `git diff`, and then decide to run `yarn install` (or `npm install` or something else) once I have everything finalized. The installation commands are much more heavyweight tasks (involving network calls etc) that I don't think should be bundled together.

**Comment by ddzz** [comment]
> Interesting idea. I'd prefer these were not tied together however. I'd rather be able to run `check-dependency-version-consistency`, review the results with `git diff`, and then decide to run `yarn install` (or `npm install` or something else) once I have everything finalized. The installation commands are much more heavyweight tasks (involving network calls etc) that I don't think should be bundled together.

Maybe an `--install` option could be added where you can specify either `yarn` or `npm`.

**Comment by bmish** [comment]
yarn or npm can be detected based on whether `yarn.lock` or `package-lock.json` is present. But still, I don't think this tool should be aware of the package manager / installation. If someone wants to do this, they can simply add this NPM script:

```
"lint:dependency-versions:fix": "check-dependency-version-consistency --fix . && yarn install"
```

**Comment by ddzz** [comment]
> yarn or npm can be detected based on whether `yarn.lock` or `package-lock.json` is present. But still, I don't think this tool should be aware of the package manager / installation. If someone wants to do this, they can simply add this NPM script:
> 
> ```
> "lint:dependency-versions:fix": "check-dependency-version-consistency --fix . && yarn install"
> ```

Good point. It might make sense to update the `README` with this script suggestion.
