### ISSUE TITLE
Allow regexp pattern to be passed for ignoring dependencies

### ISSUE THREAD

**Issue by bmish** [bmish/check-dependency-version-consistency#202]
`--ignore-dep` currently just performs an exact string match. Let's also add a `--ignore-dep-pattern` repeatable option for performing a reg exp match.

Ignore a specific dependency (existing behavior):

```
--ignore-dep my-dependency-name
```

Ignore any eslint plugin (new behavior):
```
--ignore-dep-pattern "^eslint-plugin-"
```

Note that we should avoid using the option names `--ignore` or `--ignore-pattern` as those are ambiguous about what is being ignored.

Related examples:

* https://eslint.org/docs/user-guide/command-line-interface#--ignore-pattern
* https://jestjs.io/docs/cli#--testpathignorepatternsregexarray

**Comment by ddzz** [comment]
I think a regular expression is too complicated for a CLI tool since there's a possibility of passing in an incorrect expression. A star wildcard is simpler and almost as effective as a regular expression.

**Comment by bmish** [comment]
ESLint and many other CLI tools have pattern options with regexp support. If an invalid regexp is passed, we'll throw an exception. I think we'll keep `--ignore-dep` for exact matches only, and use `--ignore-dep-pattern` for regexp pattern matches.

**Comment by bmish** [comment]
Fixed by https://github.com/bmish/check-dependency-version-consistency/pull/298.
