### ISSUE TITLE
Add option for ignoring packages

### ISSUE THREAD

**Issue by bmish** [bmish/check-dependency-version-consistency#203]
There might be some packages in a workspace that one would like to exclude/ignore from consistency checks. The goal would be to accept files/directories/globs/regexp for ignoring. We can add repeatable options:

* `--ignore-package`
* `--ignore-package-pattern`
* `--ignore-path`
* `--ignore-path-pattern`

Related examples:

* https://eslint.org/docs/user-guide/command-line-interface#--ignore-path
* https://mochajs.org/#-ignore-filedirectoryglob-exclude-filedirectoryglob
* https://jestjs.io/docs/cli#--testpathpatternregex

**Comment by tamslinn** [comment]
Hi - this option would be really useful to me, as one of the packages in my mono-repo is a legacy project with a lot of dependencies which can't be updated. Is there anything I can do to help get the PR over the line?

**Comment by bmish** [comment]
@tamslinn I'll try to implement this in the coming days.

**Comment by bmish** [comment]
Released in [v1.5.0](https://github.com/bmish/check-dependency-version-consistency/releases/tag/v1.5.0).

**Comment by tamslinn** [comment]
@bmish thanks for getting this released so quickly, really appreciated!
