### ISSUE TITLE
workspaces glob pattern not working as expected

### ISSUE THREAD

**Issue by FirstVertex** [bmish/check-dependency-version-consistency#270]
having a challenging time with the glob pattern recognition of workspaces array in package.json
pattern like "packages/ace*" yields result of
`ENOENT: no such file or directory, scandir 'packages\ace'`
there is not folder by name of ace, but there is whole bunch of folders with *prefix* of ace

i tried these patterns too
```
"packages/ace*/"
"packages/ace*/*"
"packages/ace**/*"
```

all with the same problem

**Comment by bmish** [comment]
Thanks for the report! Looks related to #249.
