### ISSUE TITLE
Rename project to `dependency-version-consistency`

### ISSUE THREAD

**Issue by ddzz** [bmish/check-dependency-version-consistency#321]

**Comment by bmish** [comment]
It's a possibility although it's a bit of a hassle to do so. What do you think the benefits would be?

We could also just provide a shorter CLI command name.

**Comment by bmish** [comment]
Closing as there's a lot of hassle and churn to renaming so I'm going to leave as-is.

Fun fact: when I started this project, I considered an even longer name: `monorepo-dependency-consistency-enforcer`.
