### ISSUE TITLE
Local package versions are not checked

### ISSUE THREAD

**Issue by kachkaev** [bmish/check-dependency-version-consistency#332]
Hey folks, great package! I’m trying it in https://github.com/blockprotocol/blockprotocol/pull/165 & https://github.com/hashintel/hash/pull/246 👍

I’ve noticed that the tool does not check dependencies on local packages. Here is an example to illustrate that:

```shell
mkdir -p /tmp/check-dependency-version-consistency-issue-332
cd /tmp/check-dependency-version-consistency-issue-332

cat << EOF > package.json
{
  "private": true,
  "workspaces": ["packages/*"],
  "dependencies": {
    "some-external-lib": "1.0.0"
  }
}
EOF

mkdir -p packages/a
mkdir -p packages/b

cat << EOF > packages/a/package.json
{
  "name": "a",
  "version": "0.4.2",
  "dependencies": {
    "some-external-lib": "1.0.1"
  }
}
EOF

cat << EOF > packages/b/package.json
{
  "name": "b",
  "version": "0.1.0",
  "dependencies": {
    "a": "0.4.1",
    "some-external-lib": "1.0.2"
  }
}
EOF

npx check-dependency-version-consistency@1.6.0 .
```

**Output**

```
Found 1 dependency with mismatching versions across the workspace. Fix with `--fix`.
╔═══════════════════╤════════╤══════════╗
║ some-external-lib │ Usages │ Packages ║
╟───────────────────┼────────┼──────────╢
║ 1.0.2             │ 1      │ b        ║
╟───────────────────┼────────┼──────────╢
║ 1.0.1             │ 1      │ a        ║
╟───────────────────┼────────┼──────────╢
║ 1.0.0             │ 1      │ (Root)   ║
╚═══════════════════╧════════╧══════════╝
```

**Expected output**

Same as above + a problem with `packages/b/package.json` → `dependencies` → `a`. We expect to see `"a": "0.4.2"` (or `"^0.4.2"` etc.) instead of `"0.4.1"`, because that’s the version we have in `packages/a/package.json`. If we don’t fix the mismatch, `yarn install` will fetch `a@0.4.1` from `npm`, which may cause pretty odd bugs in the repo 🙈

What do you think?

**Comment by bmish** [comment]
Released in [v2.0.0](https://github.com/bmish/check-dependency-version-consistency/releases/tag/v2.0.0)! Thanks for the great idea.
