### ISSUE TITLE
Error with yarn version `3.0.2`

### ISSUE THREAD

**Issue by ddzz** [bmish/check-dependency-version-consistency#354]
CDVC shows a `SyntaxError` in projects using `yarn@3.0.2`:

```
/Users/user/code/testyarn/.yarn/cache/check-dependency-version-consistency-npm-2.0.1-816826f0b3-18c136af75.zip/node_modules/check-dependency-version-consistency/dist/bin/check-dependency-version-consistency.js:3
import { run } from '../lib/cli.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/Users/user/code/testyarn/.pnp.cjs:10431:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by bmish** [comment]
What Node version are you on? This sounds like an old Node version.

**Comment by ddzz** [comment]
> What Node version are you on? This sounds like an old Node version.

14.15.0

**Comment by bmish** [comment]
What are you reproduction steps? I just tested with a fresh yarn `3.1.1` project and successfully installed and ran CDVC. If you upgraded yarn/Node in an existing project, you should delete `node_modules` and reinstall it.

**Comment by ddzz** [comment]
> What are you reproduction steps? I just tested with a fresh yarn `3.1.1` project and successfully installed and ran CDVC. If you upgraded yarn/Node in an existing project, you should delete `node_modules` and reinstall it.

* `yarn init -2`
* `yarn set version 3.0.2`
* `yarn add check-dependency-version-consistency -D`
* `yarn check-dependency-version-consistency .`

**Comment by kachkaev** [comment]
Can this be a bug in 3.0.2? What happens in you upgrade to 3.1.1?

**Comment by bmish** [comment]
Just checked and it looks like yarn `3.0.2` has this issue but yarn `3.1.1` works correctly. So they probably didn't support ESM in the older version.
