### ISSUE TITLE
Does not work with workspaces having packages as wildcard and no-hoist enabled 

### ISSUE THREAD

**Issue by bipinpoudyal** [bmish/check-dependency-version-consistency#523]
While running the check on a workspace having the packages config as wildcard (**) and no-hoist enabled, the check dependency command fails.

Expected:
It does the dependency check

Actual:
An error comes up. The error is Unexpected end of JSON input

Sample repo: I have isolated the issue and is available at https://github.com/bipinpoudyal/check-dependency-error

Additional info:
1. If I change the  ` "packages": ["packages/**"]` to  `"packages": ["packages/*"]`, it works fine.

2. I debugged a bit and found that it is failing while `accumulatePackages` in `workspace.js`. It seems to be reading from the node_modules of the packages and failing after reading `packages/package-a/node_modules/resolve/test/resolver/malformed_package_json`.

**Comment by bmish** [comment]
Thank you for the report. I'll look into this in the next week.

**Comment by bmish** [comment]
Fix in #527 is ready, please review if you can.
